In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [40]:
data = pd.read_csv('./student_activityType_sumClick.csv')
data

code_module code_presentation  id_student  resource  subpage  oucontent  \
0             AAA             2013J       11391      11.0     11.0       78.0   
1             AAA             2013J       28400       9.0     42.0      106.0   
2             AAA             2013J       30268       4.0     12.0       14.0   
3             AAA             2013J       31604      13.0     83.0      196.0   
4             AAA             2013J       32885      23.0     53.0      115.0   
...           ...               ...         ...       ...      ...        ...   
32588         GGG             2014J     2640965       4.0      6.0        4.0   
32589         GGG             2014J     2645731      67.0     20.0       61.0   
32590         GGG             2014J     2648187      14.0     14.0       21.0   
32591         GGG             2014J     2679821       9.0      6.0       11.0   
32592         GGG             2014J     2684003      10.0     20.0       38.0   

        url  forumng  quiz  page  ...  dataplus_click  externalquiz_click  \
0       4.0     52.0   0.0   0.0  ...             0.0                 0.0   
1      27.0    163.0   0.0   0.0  ...            10.0                 0.0   
2       4.0     30.0   0.0   0.0  ...             0.0                 0.0   
3      51.0    197.0   0.0   0.0  ...             2.0                 0.0   
4      13.0     77.0   0.0   0.0  ...             0.0                 0.0   
...     ...      ...   ...   ...  ...             ...                 ...   
32588   0.0      0.0   0.0   0.0  ...             0.0                 0.0   
32589   0.0     14.0  38.0   0.0  ...             0.0                 0.0   
32590   0.0      0.0  36.0   0.0  ...             0.0                 0.0   
32591   0.0     17.0   5.0   0.0  ...             0.0                 0.0   
32592   0.0     52.0  27.0   0.0  ...             0.0                 0.0   

       homepage_click  glossary_click  ouelluminate_click  dualpane_click  \
0               138.0             0.0                 0.0             0.0   
1               324.0             0.0                 0.0             0.0   
2                59.0             0.0                 0.0             0.0   
3               432.0             1.0                 0.0             0.0   
4               204.0             4.0                 0.0             0.0   
...               ...             ...                 ...             ...   
32588            22.0             0.0                 0.0             0.0   
32589           167.0             5.0                 0.0             0.0   
32590            63.0             1.0                 0.0             0.0   
32591            65.0             0.0                 0.0             0.0   
32592           120.0             0.0                 0.0             0.0   

       repeatactivity_click  htmlactivity_click  sharedsubpage_click  \
0                       0.0                 0.0                  0.0   
1                       0.0                 0.0                  0.0   
2                       0.0                 0.0                  0.0   
3                       0.0                 0.0                  0.0   
4                       0.0                 0.0                  0.0   
...                     ...                 ...                  ...   
32588                   0.0                 0.0                  0.0   
32589                   0.0                 0.0                  0.0   
32590                   0.0                 0.0                  0.0   
32591                   0.0                 0.0                  0.0   
32592                   0.0                 0.0                  0.0   

       folder_click  
0               0.0  
1               0.0  
2               0.0  
3               0.0  
4               0.0  
...             ...  
32588           0.0  
32589           0.0  
32590           0.0  
32591           0.0  
32592           0.0  

[32593 rows x 43 columns]

In [41]:
studinfo = pd.read_csv('./data/studentInfo.csv')
studinfo = studinfo[['code_module', 'code_presentation', 'id_student', 'final_result']]
studinfo

code_module code_presentation  id_student final_result
0             AAA             2013J       11391         Pass
1             AAA             2013J       28400         Pass
2             AAA             2013J       30268    Withdrawn
3             AAA             2013J       31604         Pass
4             AAA             2013J       32885         Pass
...           ...               ...         ...          ...
32588         GGG             2014J     2640965         Fail
32589         GGG             2014J     2645731  Distinction
32590         GGG             2014J     2648187         Pass
32591         GGG             2014J     2679821    Withdrawn
32592         GGG             2014J     2684003  Distinction

[32593 rows x 4 columns]

In [42]:
merge = pd.merge(studinfo, data, on=['code_module', 'code_presentation', 'id_student'], how='inner')
merge

code_module code_presentation  id_student final_result  resource  \
0             AAA             2013J       11391         Pass      11.0   
1             AAA             2013J       28400         Pass       9.0   
2             AAA             2013J       30268    Withdrawn       4.0   
3             AAA             2013J       31604         Pass      13.0   
4             AAA             2013J       32885         Pass      23.0   
...           ...               ...         ...          ...       ...   
32588         GGG             2014J     2640965         Fail       4.0   
32589         GGG             2014J     2645731  Distinction      67.0   
32590         GGG             2014J     2648187         Pass      14.0   
32591         GGG             2014J     2679821    Withdrawn       9.0   
32592         GGG             2014J     2684003  Distinction      10.0   

       subpage  oucontent   url  forumng  quiz  ...  dataplus_click  \
0         11.0       78.0   4.0     52.0   0.0  ...             0.0   
1         42.0      106.0  27.0    163.0   0.0  ...            10.0   
2         12.0       14.0   4.0     30.0   0.0  ...             0.0   
3         83.0      196.0  51.0    197.0   0.0  ...             2.0   
4         53.0      115.0  13.0     77.0   0.0  ...             0.0   
...        ...        ...   ...      ...   ...  ...             ...   
32588      6.0        4.0   0.0      0.0   0.0  ...             0.0   
32589     20.0       61.0   0.0     14.0  38.0  ...             0.0   
32590     14.0       21.0   0.0      0.0  36.0  ...             0.0   
32591      6.0       11.0   0.0     17.0   5.0  ...             0.0   
32592     20.0       38.0   0.0     52.0  27.0  ...             0.0   

       externalquiz_click  homepage_click  glossary_click  ouelluminate_click  \
0                     0.0           138.0             0.0                 0.0   
1                     0.0           324.0             0.0                 0.0   
2                     0.0            59.0             0.0                 0.0   
3                     0.0           432.0             1.0                 0.0   
4                     0.0           204.0             4.0                 0.0   
...                   ...             ...             ...                 ...   
32588                 0.0            22.0             0.0                 0.0   
32589                 0.0           167.0             5.0                 0.0   
32590                 0.0            63.0             1.0                 0.0   
32591                 0.0            65.0             0.0                 0.0   
32592                 0.0           120.0             0.0                 0.0   

       dualpane_click  repeatactivity_click  htmlactivity_click  \
0                 0.0                   0.0                 0.0   
1                 0.0                   0.0                 0.0   
2                 0.0                   0.0                 0.0   
3                 0.0                   0.0                 0.0   
4                 0.0                   0.0                 0.0   
...               ...                   ...                 ...   
32588             0.0                   0.0                 0.0   
32589             0.0                   0.0                 0.0   
32590             0.0                   0.0                 0.0   
32591             0.0                   0.0                 0.0   
32592             0.0                   0.0                 0.0   

       sharedsubpage_click  folder_click  
0                      0.0           0.0  
1                      0.0           0.0  
2                      0.0           0.0  
3                      0.0           0.0  
4                      0.0           0.0  
...                    ...           ...  
32588                  0.0           0.0  
32589                  0.0           0.0  
32590                  0.0           0.0  
32591                  0.0           0.0  
32592        

# drop those records who has no records in studentVLE table

In [43]:
merge = merge[~(merge.iloc[:, 4:].sum(axis=1)==0)]
merge

code_module code_presentation  id_student final_result  resource  \
0             AAA             2013J       11391         Pass      11.0   
1             AAA             2013J       28400         Pass       9.0   
2             AAA             2013J       30268    Withdrawn       4.0   
3             AAA             2013J       31604         Pass      13.0   
4             AAA             2013J       32885         Pass      23.0   
...           ...               ...         ...          ...       ...   
32588         GGG             2014J     2640965         Fail       4.0   
32589         GGG             2014J     2645731  Distinction      67.0   
32590         GGG             2014J     2648187         Pass      14.0   
32591         GGG             2014J     2679821    Withdrawn       9.0   
32592         GGG             2014J     2684003  Distinction      10.0   

       subpage  oucontent   url  forumng  quiz  ...  dataplus_click  \
0         11.0       78.0   4.0     52.0   0.0  ...             0.0   
1         42.0      106.0  27.0    163.0   0.0  ...            10.0   
2         12.0       14.0   4.0     30.0   0.0  ...             0.0   
3         83.0      196.0  51.0    197.0   0.0  ...             2.0   
4         53.0      115.0  13.0     77.0   0.0  ...             0.0   
...        ...        ...   ...      ...   ...  ...             ...   
32588      6.0        4.0   0.0      0.0   0.0  ...             0.0   
32589     20.0       61.0   0.0     14.0  38.0  ...             0.0   
32590     14.0       21.0   0.0      0.0  36.0  ...             0.0   
32591      6.0       11.0   0.0     17.0   5.0  ...             0.0   
32592     20.0       38.0   0.0     52.0  27.0  ...             0.0   

       externalquiz_click  homepage_click  glossary_click  ouelluminate_click  \
0                     0.0           138.0             0.0                 0.0   
1                     0.0           324.0             0.0                 0.0   
2                     0.0            59.0             0.0                 0.0   
3                     0.0           432.0             1.0                 0.0   
4                     0.0           204.0             4.0                 0.0   
...                   ...             ...             ...                 ...   
32588                 0.0            22.0             0.0                 0.0   
32589                 0.0           167.0             5.0                 0.0   
32590                 0.0            63.0             1.0                 0.0   
32591                 0.0            65.0             0.0                 0.0   
32592                 0.0           120.0             0.0                 0.0   

       dualpane_click  repeatactivity_click  htmlactivity_click  \
0                 0.0                   0.0                 0.0   
1                 0.0                   0.0                 0.0   
2                 0.0                   0.0                 0.0   
3                 0.0                   0.0                 0.0   
4                 0.0                   0.0                 0.0   
...               ...                   ...                 ...   
32588             0.0                   0.0                 0.0   
32589             0.0                   0.0                 0.0   
32590             0.0                   0.0                 0.0   
32591             0.0                   0.0                 0.0   
32592             0.0                   0.0                 0.0   

       sharedsubpage_click  folder_click  
0                      0.0           0.0  
1                      0.0           0.0  
2                      0.0           0.0  
3                      0.0           0.0  
4                      0.0           0.0  
...                    ...           ...  
32588                  0.0           0.0  
32589                  0.0           0.0  
32590                  0.0           0.0  
32591                  0.0           0.0  
32592        

In [44]:
courses = list(merge['code_module'].unique())
times = list(merge['code_presentation'].unique())
course_map = {course:i for i, course in enumerate(courses, start=1)}
times_map = {time:i for i, time in enumerate(times, start=1)}
print(course_map, times_map)

{'AAA': 1, 'BBB': 2, 'CCC': 3, 'DDD': 4, 'EEE': 5, 'FFF': 6, 'GGG': 7} {'2013J': 1, '2014J': 2, '2013B': 3, '2014B': 4}


In [45]:
merge['final_result'] = merge['final_result'].map({'Pass':1, 'Distinction':2, 'Fail':0, 'Withdrawn':0})
merge['code_module'] = merge['code_module'].map(course_map)
merge['code_presentation'] = merge['code_presentation'].map(times_map)

X = merge.drop(columns=['id_student', 'final_result'])
y = merge['final_result']

<ipython-input-45-da2877556e5f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge['final_result'] = merge['final_result'].map({'Pass':1, 'Distinction':2, 'Fail':0, 'Withdrawn':0})
<ipython-input-45-da2877556e5f>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge['code_module'] = merge['code_module'].map(course_map)
<ipython-input-45-da2877556e5f>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See 

In [46]:
X.shape, y.shape

((29228, 42), (29228,))

In [47]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

In [50]:
# Random forest classifier
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [51]:
# predict
predict = rfc.predict(X_test)
print('#### confusion metrix ####')
print(confusion_matrix(predict, y_test))
print('####### Classification report #######')
print(classification_report(predict, y_test))

#### confusion metrix ####
[[2320  218   22]
 [ 446 2192  526]
 [   3   62   57]]
####### Classification report #######
              precision    recall  f1-score   support

           0       0.84      0.91      0.87      2560
           1       0.89      0.69      0.78      3164
           2       0.09      0.47      0.16       122

    accuracy                           0.78      5846
   macro avg       0.61      0.69      0.60      5846
weighted avg       0.85      0.78      0.81      5846



# Support Vector Classifier

In [52]:
svc = SVC()
svc.fit(X_train, y_train)

SVC()

In [53]:
# predict
predict = svc.predict(X_test)
print('#### confusion metrix ####')
print(confusion_matrix(predict, y_test))
print('####### Classification report #######')
print(classification_report(predict, y_test))

#### confusion metrix ####
[[2264  452   49]
 [ 504 2007  542]
 [   1   13   14]]
####### Classification report #######
              precision    recall  f1-score   support

           0       0.82      0.82      0.82      2765
           1       0.81      0.66      0.73      3053
           2       0.02      0.50      0.04        28

    accuracy                           0.73      5846
   macro avg       0.55      0.66      0.53      5846
weighted avg       0.81      0.73      0.77      5846



# Gradient Boost Classifier

In [54]:
gbc = GradientBoostingClassifier()
gbc.fit(X_train, y_train)

GradientBoostingClassifier()

In [56]:
# predict
predict = gbc.predict(X_test)
print('#### confusion metrix ####')
print(confusion_matrix(predict, y_test))
print('####### Classification report #######')
print(classification_report(predict, y_test))

#### confusion metrix ####
[[2286  236   20]
 [ 477 2189  521]
 [   6   47   64]]
####### Classification report #######
              precision    recall  f1-score   support

           0       0.83      0.90      0.86      2542
           1       0.89      0.69      0.77      3187
           2       0.11      0.55      0.18       117

    accuracy                           0.78      5846
   macro avg       0.61      0.71      0.60      5846
weighted avg       0.84      0.78      0.80      5846



# Deep Learning Approach using Tensorflow

In [59]:
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Model, Sequential
from tensorflow.keras.utils import to_categorical

In [72]:
model = Sequential()
model.add(Input(shape=(X_train.shape[1], )))
model.add(Dense(32, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [73]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [74]:
model.fit(X_train, to_categorical(y_train), validation_split=0.2, epochs=20, batch_size=32, verbose=2)

Epoch 1/20
585/585 - 1s - loss: 1.2461 - accuracy: 0.5195 - val_loss: 0.8207 - val_accuracy: 0.6583
Epoch 2/20
585/585 - 1s - loss: 0.8028 - accuracy: 0.6530 - val_loss: 0.7567 - val_accuracy: 0.6801
Epoch 3/20
585/585 - 1s - loss: 0.7395 - accuracy: 0.6858 - val_loss: 0.7914 - val_accuracy: 0.6318
Epoch 4/20
585/585 - 1s - loss: 0.7228 - accuracy: 0.6898 - val_loss: 0.8032 - val_accuracy: 0.6273
Epoch 5/20
585/585 - 1s - loss: 0.7071 - accuracy: 0.7025 - val_loss: 0.7205 - val_accuracy: 0.6919
Epoch 6/20
585/585 - 1s - loss: 0.7150 - accuracy: 0.7001 - val_loss: 0.6985 - val_accuracy: 0.7103
Epoch 7/20
585/585 - 1s - loss: 0.6739 - accuracy: 0.7264 - val_loss: 0.7717 - val_accuracy: 0.6483
Epoch 8/20
585/585 - 1s - loss: 0.6588 - accuracy: 0.7332 - val_loss: 0.6437 - val_accuracy: 0.7533
Epoch 9/20
585/585 - 1s - loss: 0.6492 - accuracy: 0.7385 - val_loss: 0.6445 - val_accuracy: 0.7419
Epoch 10/20
585/585 - 1s - loss: 0.6509 - accuracy: 0.7354 - val_loss: 0.6332 - val_accuracy: 0.7486

In [75]:
predict = model.predict(X_test)
predict = np.argmax(predict, axis=1)
print('#### confusion metrix ####')
print(confusion_matrix(predict, y_test))
print('####### Classification report #######')
print(classification_report(predict, y_test))

#### confusion metrix ####
[[2219  235   28]
 [ 550 2237  577]
 [   0    0    0]]
####### Classification report #######
              precision    recall  f1-score   support

           0       0.80      0.89      0.85      2482
           1       0.90      0.66      0.77      3364
           2       0.00      0.00      0.00         0

    accuracy                           0.76      5846
   macro avg       0.57      0.52      0.54      5846
weighted avg       0.86      0.76      0.80      5846



/home/ramesh/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
